# Generated by cucumber-sinatra. (2015-01-06 21:12:03 +0000)

ENV['RACK_ENV'] = 'test'

require File.join(File.dirname(__FILE__), '..', '..', 'lib/domination.rb')

require 'capybara'
require 'capybara/cucumber'
require 'rspec'

Capybara.app = Domination

class DominationWorld
  include Capybara::DSL
  include RSpec::Expectations
  include RSpec::Matchers
end

World do
  DominationWorld.new
end
